sdfsdf

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,42 +1,32 @@
 #!/usr/bin/env bash
-# install load balancer
 
+# Exit on any command failure
+set -e
 
-c1='\e[0m'
-c2='\e[1;32m'
-c3='\e[31m'
-function install() {
-	command -v "$1" &> /dev/null
-	if [ $? -ne 0 ]; then
-		sudo apt-get update -y -qq && \
-			sudo apt-get install -y "$1" -qq
-		echo -e "\n"
-	else
-		echo -e "	${c2}${1} is already installed.${c3}\n"
-	fi
-}
-install haproxy
-sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
-server_config=\
-"
-defaults
-  mode http
-  timeout client 15s
-  timeout connect 10s
-  timeout server 15s
-  timeout http-request 10s
-frontend qubitket-tech-frontend
-    bind *:80
-    default_backend qubitket-tech-backend
-backend qubitket-tech-backend
+# Check if HAProxy is already installed
+if ! command -v haproxy &> /dev/null; then
+    sudo apt-get install -y haproxy
+else
+    echo "HAProxy is already installed."
+fi
+
+# Configure HAProxy
+cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
+frontend qubitket.tech
+    timeout client  30000
+    bind 0:80
+    default_backend qubitket.tech_backend
+
+backend qubitket.tech_backend
+    timeout connect  3000
+    timeout server  30000
     balance roundrobin
     server 238549-web-01 100.27.0.247:80 check
     server 238549-web-02 100.26.162.119:80 check
-"
-echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
-echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
-if [ "$(pgrep -c haproxy)" -le 0 ]; then
-	sudo service haproxy start
-else
-	sudo service haproxy restart
-fi
+EOT
+
+# Check HAProxy configuration and restart the service
+sudo haproxy -c -f /etc/haproxy/haproxy.cfg && sudo service haproxy restart
+
+# Disable the exit-on-error behavior if you want to continue the script even after an error
+set +e
